spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "local db url"
    username: "db username"
    password: "db password"



  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        show-sql: true

  # 로그 레벨 설정
  logging:
    level:
      # hibernate 가 남기는 모든 로그가 debug모드로 설정
      # jpa hibernate가 생성하는 sql이 로거를 통해서 찍히도록 하는 설정
      org.hibernate.SQL: debug
      org.hibernate.type: trace # 실제 들어가는 파라미터값 찍어주는 설정
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8088